version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      meetplan:
        aliases:
          - postgres
    volumes: 
      - ./MeetPlanDB:/var/lib/postgresql/data
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    networks:
      meetplan:
        aliases:
          - nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  frontend:
    image: ghcr.io/meetplan/frontend
    depends_on:
      - backend
    networks:
      meetplan:
        aliases:
          - frontend
  backend:
    image: ghcr.io/meetplan/backend
    volumes:
      - ./config.json:/app/config.json
      - ./cacerts:/app/cacerts
      - ./protonConfig.json:/app/protonConfig.json
      - ./icons:/app/icons
      - ./documents:/app/documents
    restart: always
    depends_on:
      - postgres
    networks:
      meetplan:
        aliases:
          - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-proxy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  meetplan:

volumes:
  certbot-etc:
  certbot-var:
  web-root:
