version: '3.8'
services:
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      meetplan:
        aliases:
          - nginx
    ports:
      - "80:80"
      - "443:443"
  frontend:
    image: ghcr.io/meetplan/frontend
    networks:
      meetplan:
        aliases:
          - frontend
  backend:
    image: ghcr.io/meetplan/backend
    volumes:
      - ./MeetPlanDB:/app/MeetPlanDB
    environment:
      - MP_HOST=0.0.0.0:80
    networks:
      meetplan:
        aliases:
          - backend
networks:
  meetplan:
