version: '3.8'
services:
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    networks:
      meetplan:
        aliases:
          - nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  frontend:
    image: ghcr.io/meetplan/frontend
    networks:
      meetplan:
        aliases:
          - frontend
  backend:
    image: ghcr.io/meetplan/backend
    volumes:
      - ./MeetPlanDB:/app/MeetPlanDB
    environment:
      - MP_HOST=0.0.0.0:80
    networks:
      meetplan:
        aliases:
          - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-proxy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  meetplan:

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/<yourusername>/MeetPlanDocker/dhparam/
      o: bind