version: '3.8'
services:
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      meetplan:
        aliases:
          - nginx
    ports:
      - "80:80"
      - "443:443"
  frontend:
    image: ghcr.io/meetplan/frontend
    networks:
      meetplan:
        aliases:
          - frontend
  backend:
    image: ghcr.io/meetplan/backend
    volumes:
      - ./MeetPlanDB:/app/MeetPlanDB
    environment:
      - MP_HOST=0.0.0.0:80
    networks:
      meetplan:
        aliases:
          - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-proxy
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN_NAME}
networks:
  meetplan:

volumes:
  certbot-etc:
  certbot-var:
  web-root:
